import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthProvider } from '@/contexts/Auth.context';
import { MessageProvider } from '@/contexts/Message.context';
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

import Navbar from '../components/nav/navbar.component'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' text-black' + ' min-w-[1200px]'}>
        <AuthProvider>
          <MessageProvider>
            <Navbar></Navbar>
            {children}
          </MessageProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
