export default interface LeaguePositionAverages {
    id: number;
    position: string;
    season: number;
    passing_yards: number;
    air_yards: number;
    passing_yards_after_catch: number;
    passing_attempts: number;
    passing_completions: number;
    passing_touchdowns: number;
    passing_interceptions: number;
    passer_rating: number;
    rushing_attempts: number;
    rushing_yards: number;
    rushing_touchdowns: number;
    targets: number;
    receptions: number;
    receiving_yards: number;
    receiving_yards_after_catch: number;
    receiving_touchdowns: number;
    return_attempts: number | null;
    return_yards: number | null;
    return_touchdowns: number | null;
    yards_per_passing_attempt: number;
    yards_per_passing_completion: number;
    air_yards_per_passing_attempt: number;
    air_yards_per_passing_completion: number;
    yards_after_catch_per_reception: number | null;
    yards_per_rush: number;
    yards_per_reception: number;
    yards_per_target: number;
    yards_per_return: number | null;
    passing_epa: number;
    rushing_epa: number;
    receiving_epa: number;
    fumbles: number;
    fumbles_lost: number;
    sacks_allowed: number;
    createdAt: string;
    updatedAt: string;
}